Author: Jinzhe Zhang



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load("tidyverse","hurricaneexposuredata","drat","maps","tmap","sf","viridis","sp")


```


```{r}
 #Extract data for the mapping
addRepo("geanders")
data("hurr_tracks")
data("rain")
head(hurr_tracks)
head(rain)
```



```{r message=FALSE, warning=FALSE}
Floyd_track <- hurr_tracks %>% filter(storm_id=="Floyd-1999")
Allison_Track <- hurr_tracks %>% filter(storm_id=="Allison-2001")

Floyd_Rain <- rain %>% filter(storm_id=="Floyd-1999") %>% group_by(fips,storm_id) %>%
  summarise(precip_total=sum(precip))
Allison_Rain <- rain %>%filter(storm_id=="Allison-2001") %>%group_by(fips,storm_id) %>%
  summarise(precip_total=sum(precip))
```

```{r}

Fips_Counties <- county.fips
# Here the fips is in numerical type
Fips_Counties$fips <- as.character(Fips_Counties$fips)
# To add the 0 in front of the fips use str_pad.
Fips_Counties$fips <- str_pad(Fips_Counties$fips,5,side = "left",pad = "0")
```


```{r}
Floy_table <- merge(Floyd_Rain,Fips_Counties,by="fips") %>% separate(polyname, into= c("region","subregion"),sep= ",")
Allison_table <- merge(Allison_Rain, Fips_Counties, by="fips") %>% separate(polyname,
                                                                            into=c("region","subregion"),sep=",")
```




```{r}

State_name <- c("texas","oklahoma","kansas","louisiana","arkansas","missouri","iowa","wisconsin","michigan","illinois","indiana","ohio","kentucky","tennessee","alabama","mississippi","florida","georgia","south carolina","north carolina","virginia","west virginia","maryland","delaware","pennsylvania","new jersey","new york","connecticut","rhode island","massachusetts","vermont","new hampshire","maine")
Effected_states <- map_data("county",State_name)


Floyd1999 <- merge(Effected_states,Floy_table,by=c("region","subregion"))
Floyd1999[Floyd1999==0.0] <- 0
Floyd1999$rain_cut <- cut(Floyd1999$precip_total,breaks=c(0,20,40,60,80,100,120,140,160,180))

Allison2001 <- merge(Effected_states,Allison_table,by=c("region","subregion"))
Allison2001[Allison2001==0.0] <- 0

Allison2001$rain_cut <- ifelse(Allison2001$precip_total>175,"Exposed","Unexposed")
```

### 2.1 Floyd-1999 ggplot

```{r warning=FALSE}
Floyd1999Plot <- ggplot() + 
  geom_polygon(data=Effected_states, aes(x=long, y=lat, group=group),colour="white",fill="gray") + 
  geom_polygon(data=Floyd1999,aes(x=long,y=lat,group=group,fill=rain_cut))+
  
  geom_path(data=Floyd_track,aes(x=longitude, y= latitude),color="red")
  

```

```{r message=FALSE, warning=FALSE}
Floyd1999Plot + labs(fill="Rainfall(mm)") + scale_fill_brewer(palette="Blues") +ggtitle("Floyd-1999") + theme(plot.title = element_text(hjust = 0.5))
```

### 2.2 Allison-2001 ggplot

```{r}
Allison2001Plot <- ggplot() + 
  geom_polygon(data=Effected_states, aes(x=long, y=lat, group=group),colour="white",fill="gray") + 
  
  geom_path(data=Allison_Track,aes(x=longitude, y=latitude),color="black")+
  
  geom_polygon(data=Allison2001,aes(x=long,y=lat,group=group,fill=rain_cut))+scale_fill_manual(values = c("black", "pink"))
  
 
  

```

```{r}
Allison2001Plot + labs(fill="Rain > 175mm") +  
  xlab("Long") + ylab("Lat") +
  ggtitle("Allison-2001") + 
  theme(plot.title = element_text(hjust = 0.5))
```

## 3.  tmap Floyd

```{r}

T_map <- st_as_sf(map("county",State_name,plot=F,fill=T))


TFloyd <- Floyd1999 %>% select(region,subregion,rain_cut) %>% mutate(ID=str_c(region,subregion,sep = ",")) %>%    
  select(ID,rain_cut) %>% 
  rename(`Rainfall(mm)`=rain_cut)
T_Floyd1999 <- left_join(T_map,TFloyd,by="ID")


T_Floyd_track=cbind(Floyd_track$longitude,Floyd_track$latitude)%>%
  Line() %>% Lines(ID='Floyd-1999') %>%
  list() %>% SpatialLines()

```

```{r}
T_Floyd1999 <- tm_shape(T_Floyd1999)+ tm_polygons(border.col="black",lwd=0.1,col='Rainfall(mm)',style="cont",
              title="Rainfall(mm)",
              palette=cividis(n=9,direction=-1))+
  tm_shape(T_Floyd_track) +
  tm_lines(col='red')

T_Floyd1999 + tm_layout(main.title='Floyd-1999')
           
```

### Allison-2001 tmap

```{r}

T_Allison <- Allison2001 %>% 
  select(region,subregion,rain_cut) %>% 
  mutate(ID=str_c(region,subregion,sep = ",")) %>% 
  select(ID,rain_cut) %>% 
  rename(`Rainfall > 175mm`=rain_cut)
T_Allison2001 <- left_join(T_map,T_Allison,by="ID")

tAllison_Track=cbind(Allison_Track$longitude,Allison_Track$latitude) %>%
  Line() %>% Lines(ID='Floyd-1999') %>%
  list() %>% SpatialLines()
```


```{r}
T_Allison2001Plot <- 
tm_shape(T_Allison2001)+tm_polygons(border.col="white",lwd=0.1,col='Rainfall > 175mm',style="cont",
                                    title="Rainfall > 175mm",
              palette=plasma(n=3,direction=-1))+
  tm_shape(tAllison_Track) +
  tm_lines(col='green')


T_Allison2001Plot + tm_layout(main.title='Allison-2001')
           


```
