---
output:
  word_document: default
  html_document: default
---



```{r setup, include=FALSE}

pacman::p_load("learnr","foreign","knitr","arm","ggplot2")
```



```{r}

# For the understanding of the question:

# The climate can be influenced by many factors such as CO2, industrial emission. The data source such as ATMP,WTMP..etc that I used to analyze just the results of climate changes. Those results or data may have positive or negative relationship with the climate changes. Normally, the range of time in the data set is general scale on hundred of years, which means we need much more data to conclude the climate change in this area. I did not expect the trendency of factors changing is very obvious due to I only accessed 30 years data. However, it is still enought to interpret somthing.




#For approaching: 

# I use one year as the unit of time interval because I think the climate change is a slow process which shouold be reflected on the annual scale.Furthermore, calculating the data on annual scale could minimize the effect of extreme data or temperature on the particular date.Here I collected the data set which contains the factors like:ATMP,BAR,WTMP from 1987 to 2016. I found out that the data in 1987 only contain one month which is December. To smooth the regression line later, I decide to drop this month when I fit the regresion line. Of course, before calculating and summarizing the data, I noticed that there are some errors such as 999 in water or air temperature. Then I remove those rows from the data set.There are three main signals that Annual_WTMP,Annual_ATMP and difference between previous two. The reason I pick those three temperatures as signals is that the difference between air and water temperature creates the atmospheric pressure difference, then cause wind and rain.That is also why those factors could show the climate changes indeedly. 

library(lubridate)
# From the original sources, we found that the data are not organized and clean.

# By using the document which was created by Zhe Yu, we organized and cleaned data source, then I loaded data set MR_DATE into R.


# Load the data
Bouy=read.csv("MR_DATE.csv")

#Using the function ymd_hms() in lubridate package to access POSIX type data.
time=ymd_hms(Bouy$DATETIME)

#Using year() function to get years of each date.
Bouy$year=year(time)

#Here I found out that there are some extreme data or error (which exceed 100 as temperature)in the data set.
#Then remove all rows which contain temperature higher than 100.
Bouy=Bouy[Bouy$WTMP<100,]

Bouy=Bouy[Bouy$ATMP<100,]


#There are some mistakes that the 1998 year was modified to 3898 in the previous steps. So here I subtracted 1900 for every row which contain 3898 
for( i in 1:length(Bouy$year)){
  
   if (Bouy$year[i]>3000){
    
      Bouy$year[i]= Bouy$year[i]-1900
   }
  
}



# Using two index indicators and a function to calculate the index of beginning and end for each year. 
before=0
count=0

le=function(x){
  for(i in 1:length(Bouy$year)){

    if ( Bouy$year[i]<x){
      before=before+1
    }
    if ( Bouy$year[i]==x){
      count=count+1
    }
    
  }
  return(c(before,count))
}


#Create two container to contain average annual temperature values.
Anual_WTMP=sample(1,30,replace = TRUE)

Anual_ATMP=sample(1,30,replace = TRUE)

#Assign the values to each container
for(i in 1:30){
  
  Anual_WTMP[i]=mean(Bouy$WTMP[le(1987+i-1)[1]+1:le(1987+i-1)[2]])
  
  Anual_ATMP[i]=mean(Bouy$ATMP[le(1987+i-1)[1]+1:le(1987+i-1)[2]])
}
# Label for x-axis
x=c(1987:2016)

# Calculate the  average temperature of those 30 years.

Anual=mean(Bouy$ATMP)
Anual2=mean(Bouy$WTMP)

# Because the 1987 year only have data in December so I drop it by using index [2:30]
data=data.frame(x[2:30],Anual_ATMP[2:30])
data2=data.frame(x[2:30],Anual_WTMP[2:30])

#Here I want to show the difference between air temperature and water temperature on average.
data3=data.frame(x[2:30],c(Anual_WTMP-Anual_ATMP)[2:30])


#Conclusion:
#The climate changed from 1987 to 2016.The specific heat capacity of water is large. Generally speaking, its anual temperature will not change significantly. However, I can see the water temperature is increasing as the date is approaching to 2016, which means the climate did changed in the past 30 years.Meacnwhile the average difference between air and water temperatures also increased. 

# As I mentioned above,after searching on the other researches about climate changes, I found that the range of 30 years may still too short to show the change of climate obviously. Next time, I may try to analyze with 100 years data.


#Try to center the data of temperature by subtracting the average temperature of those 30 years.
ggplot(data,aes(x[2:30],Anual_ATMP[2:30]-Anual))+geom_smooth(aes(x[2:30],Anual_ATMP[2:30]-Anual),method="lm")+geom_point(aes(x[2:30],Anual_ATMP[2:30]-Anual))+ggtitle("Annual Air Temperaute")

ggplot(data2,aes(x[2:30],Anual_WTMP[2:30]-Anual2))+geom_smooth(aes(x[2:30],Anual_WTMP[2:30]-Anual2),method="lm")+ggtitle("Annual Water Temperaute")



# Here the plots show the air temperatures are tending to decrease while the water temperatures are increasing.

ggplot(data3,aes(x[2:30],c(Anual_WTMP-Anual_ATMP)[2:30]))+geom_smooth(aes(x[2:30],c(Anual_WTMP-Anual_ATMP)[2:30]),method = "lm")+geom_point(aes(x[2:30],c(Anual_WTMP-Anual_ATMP)[2:30]))+ggtitle("Annual Difference Temperaute")

# Here the plots show the air temperatures are tending to decrease while the water temperatures are increasing.

```




